blank_issues_enabled: false
contact_links:
  - name: 💬 Star Citizen Community & Fragen
    url: https://github.com/gOOvER/SCLogMate/discussions
    about: Stelle Fragen oder diskutiere mit anderen Piloten über SCLogMate.
